// app/layout.js

import { Geist, Poppins, Roboto, Montserrat, DM_Sans } from "next/font/google";
import "./globals.css";

// Initialize Poppins
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

// Initialize Roboto
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

const montserrat = Montserrat({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const dmSans = DM_Sans({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-dm-sans",
  display: "swap",
});

// Initialize Geist
const geist = Geist({
  subsets: ["latin"],
});

// Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geist.className} ${poppins.variable} ${roboto.variable} ${roboto.variable} ${montserrat.variable}  ${dmSans.variable}`}
    >
      <body className="">{children}</body>
    </html>
  );
}
